=== Rose21/KP/xml/dtd.dtd
<!ELEMENT note (tytul, autors, spis_tresci)>
        <!ELEMENT tytul (#PCDATA)>
        <!ELEMENT autors (autor, autor)>
                <!ELEMENT autor (#PCDATA)>
        <!ELEMENT spis_tresci (rozdzial*)>
                <!ELEMENT rozdzial (name, page, fragment?)>
                        <!ELEMENT name (#PCDATA)>
                        <!ELEMENT page (#PCDATA)>
                        <!ELEMENT fragment (orginal, tlumaczenie)>
                                <!ELEMENT orginal (#PCDATA)>
                                <!ELEMENT tlumaczenie (#PCDATA)>

=== Rose21/KP/xml/dtd.xml
<!DOCTYPE biblioteka SYSTEM "dtd.dtd">
<note>
      	<tytul>Eona. Ostatni lord Smocze Oko</tytul>
        <autors>
                <autor>Alison Goodman</autor>
                
        </autors>

        <spis_tresci>
                <rozdzial>
                        <name>Prolog</name>
                        <page>5</page>
                        <fragment>
                                <orginal>
                                	Tutaj powinno znaleźć się angielski prolog, ale nie mogłam nigdzie znaleźć pdfa książki.
                                </orginal>
                                <tlumaczenie>
				Spisane ręką Prahna - cesarskiego bibliotekarza i nauczyciela jego wysokości Księcia
					Kygo, prawowitego spadkobiercy cesarskiego tronu.
		
				Pewien mędrzec napisał, że pierwszą ofiarą wojny jest prawda. Dlatego właśnie daję
				rzetelny opis przejęcia cesarskiego pałacu i tronu przez wielkiego lorda Sethona, co nastąpiło
				nazajutrz po śmierci jego brata, czcigodnego Cesarza Pokoju i Harmonii.

				Byłem świadkiem brutalnego najazdu wojska na pałac i widziałem śmierć wielu
				moich braci eunuchów, którzy nie podnieśli broni na swoją obronę. Widziałem, jak
				wtargnięto do haremu, wycięto w pień cesarską gwardię i prześladowano dworzan. Serce
				rozdzierało się we mnie, kiedy ginęło dziecię będące drugim w kolejności następcą tronu i
				gdy sam wielki lord Sethon mordował jego matkę. Jak mówi oficjalny raport, książę Kygo,
				pierwszy w kolejności następca tronu, wyniesiony do godności perłowego cesarza tuż przed
				krwawym zamachem stanu, zginął w czasie bitwy. Wszelako jego ciało nie zostało
				znalezione, a do mnie dotarła pogłoska, że ocalał wraz z niedobitkami swej gwardii. Oby to
				była prawda, boskimi ustami głoszona!
		
				Zaświadczam natomiast, że lord Ido - szczurzy lord Smocze Oko - w batalii o władzę
				osobiście pozbawił życia prawie wszystkich pozostałych lordów Smocze Oko, przy czym nie
				oszczędził nawet ich uczniów. Widziałem ich zwłoki, ale też, jak wszyscy zresztą, czułem
				drżenie ziemi i słyszałem gromy na niebie, bezsprzecznie świadczące o smutku dziesięciu
				smoków. Z grona lordów Smocze Oko przy życiu pozostał jedynie zdrajca lord Ido oraz lord
				Eon, nowy lustrzany lord Smocze Oko, którego widziano, gdy uchodził z pałacu. Przypuszcza
				się, że uciekł również Dillon, uczeń lorda Ido. Nie wiadomo, czy i Dillona, podobnie jak jego
				pana, trawi gorączka władzy, ale jeśli rzeczywiście żyje, rychło zostanie szczurzym lordem
				Smocze Oko, bowiem lord Ido, który próbował pokrzyżować szyki wielkiemu lordowi
				Sethonowi, obecnie siedzi w pałacowych lochach. Niektórzy mówią, że nie może posługiwać
				się swoją mocą, więc jest zdany na łaskę i niełaskę rozwścieczonego wielkiego lorda.

                               

                                </tlumaczenie>
                        </fragment>
                </rozdzial>
                <rozdzial>
                        <name>ROZDZIAŁ 1</name>
                        <page>8</page>
                        <fragment>
                                <orginal>
                                        Tutaj powinno znaleźć się angielski rozdzial I, ale nie mogłam nigdzie znaleźć pdfa książki.
                                </orginal>
                                <tlumaczenie>
                                        Smoki płakały.
					Patrzyłam na szare, lekko wzburzone morze, lecz moja uwaga była skupiona na
					cichych dźwiękach, które rozlegały się gdzieś we mnie. Po raz trzeci z rzędu, odkąd
					uciekliśmy ze zdobytego pałacu, stałam o świcie na tej samej skale, wsłuchana w lamenty
					dziesięciu osieroconych zwierząt. Zwykle było to nikłe zawodzenie, przygłuszone srebrzystą
					pieśnią Lustrzanego Smoka. Tego ranka wszakże zawodziły głośniej.

					
                                </tlumaczenie>
                        </fragment>
                </rozdzial>
                <rozdzial>
                        <name>ROZDZIAŁ 2</name>
                        <page>27</page>
                </rozdzial>
                <rozdzial>
                        <name>ROZDZIAŁ 3</name>
                        <page>34</page>
                </rozdzial>
                <rozdzial>
                        <name>ROZDZIAŁ 4</name>
                        <page>47</page>
                        <fragment>
                                <orginal>
                                        Nie znalazłam tłumaczniea
                                </orginal>
                                <tlumaczenie>
                                        Rosły mężczyzna na chwiejnych nogach wtoczył się do środka, ciężko, chrapliwie
					oddychając. Upuścił miecz i zgiął się wpół. Lady Dela podbiegła do niego.
					- Jesteś ranny!
					- Nie. - Chwycił jej wyciągniętą rękę i przytrzymał ją na odległość ramienia. - To
					drobiazg. - Łapczywie chwytał powietrze. - Perłowy cesarz jest na dole.
					- W zajeździe? - zdumiała się Vida. - Co tu robi? Oblicze Ryka jawiło się posępne w
					świetle księżyca.
					- Kiedy dotarłem do Jego Cesarskiej Mości, powiedziałem mu, że Sethon zamordował
					jego matkę i brata. Wpadł w szał. Jakby zaślepiła go zemsta. Zabił dwóch przybocznych
					gwardzistów, a potem przybył tutaj w poszukiwaniu ludzi Sethona. Zabija każdego, który mu
					się nawinie, każdego!
					- Jeśli zginie, wszystko będzie stracone - stwierdziła Vida. Wpatrywałam się w
					zdobione nefrytami i księżycowymi kamieniami rękojeści mieczy, które trzymałam w
					dłoniach. Ich mętne lśnienie przeobraziło się w wizję perły wszytej w szyję pod gardłem
					cesarza Kygo. Potrząsnęłam głową, próbując wymazać ten obraz z moich myśli. Rozmył się,
					lecz w mojej głowie u podstawy czaszki umiejscowił się cichy szum.
					- Musimy go powstrzymać, rozbroić - mówiła Vida. - I zabrać stąd.
					- Rozbroić? - odparł Ryko. - Nie wolno nam grozić bronią cesarzowi. - Starł krew z
					powiek. - Dela, zaprowadź Eonę w bezpieczne miejsce. Spieszcie się, póki walki trwają tylko
					na dziedzińcu.
					- Nigdzie się stąd nie ruszam - oświadczyłam. - Musimy powstrzymać cesarza. - Szum
					się nasilał.
                                </tlumaczenie>
                        </fragment>
                </rozdzial>
                <rozdzial>
                        <name>ROZDZIAŁ 5</name>
                        <page>59</page>
                </rozdzial>
                <rozdzial>
                        <name>ROZDZIAŁ 6</name>
                        <page>72</page>
                </rozdzial>
                <rozdzial>
                        <name>ROZDZIAŁ 7</name>
                        <page>88</page>
                </rozdzial>
                <rozdzial>
                        <name>ROZDZIAŁ 8</name>
                        <page>105</page>
                </rozdzial>
                <rozdzial>
                        <name>ROZDZIAŁ 9</name>
                        <page>120</page>
                </rozdzial>
                <rozdzial>
                        <name>ROZDZIAŁ 10</name>
                        <page>140</page>
                </rozdzial>
                <rozdzial>
                        <name>ROZDZIAŁ 11</name>
                        <page>154</page>
                </rozdzial>
                <rozdzial>
                        <name>ROZDZIAŁ 12</name>
                        <page>168</page>
                </rozdzial>
                <rozdzial>
                        <name>ROZDZIAŁ 13</name>
                        <page>190</page>
                </rozdzial>
		<rozdzial>
			<name>ROZDZIAŁ 14</name>
			<page>208</page>
		</rozdzial>
                <rozdzial>
                        <name>OD AUTORKI</name>
                        <page>432</page>
                </rozdzial>
        </spis_tresci>
</note>
